#!/bin/bash
#
# The D-AI-LY - Autonomous Daily Pipeline
#
# This script orchestrates the full workflow:
# 1. Discover newsworthy tables
# 2. Fetch data for selected table(s)
# 3. Generate articles (via Claude Code)
# 4. Build and publish site
#
# Usage: ./run_daily.sh [--dry-run] [--table TABLE_NUMBER]
#
# Options:
#   --dry-run     Run discovery only, don't generate or publish
#   --table NUM   Skip discovery and process specific table

set -e

# Configuration
OUTPUT_DIR="output"
DOCS_DIR="docs"

# Parse arguments
DRY_RUN=false
SPECIFIC_TABLE=""

for arg in "$@"; do
  case $arg in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --table)
      SPECIFIC_TABLE="$2"
      shift 2
      ;;
    --table=*)
      SPECIFIC_TABLE="${arg#*=}"
      shift
      ;;
  esac
done

echo "═══════════════════════════════════════════════════════════════════"
echo "  THE D-AI-LY - Autonomous Pipeline"
echo "  $(date '+%Y-%m-%d %H:%M:%S')"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Step 1: Discover topics (or use specific table)
if [ -n "$SPECIFIC_TABLE" ]; then
  echo "📌 Using specified table: $SPECIFIC_TABLE"
  SELECTED_TABLE="$SPECIFIC_TABLE"
else
  echo "🔍 Step 1: Discovering newsworthy topics..."
  Rscript r-tools/discover_topics.R --configured --json --output="$OUTPUT_DIR"

  # Read recommendation from JSON
  if [ -f "$OUTPUT_DIR/discovery_results.json" ]; then
    SELECTED_TABLE=$(python3 -c "
import json
with open('$OUTPUT_DIR/discovery_results.json') as f:
    data = json.load(f)
    if data.get('recommendation'):
        print(data['recommendation']['table_number'])
")
    echo ""
    echo "📊 Recommended table: $SELECTED_TABLE"
  else
    echo "❌ Discovery failed - no results file"
    exit 1
  fi
fi

if [ -z "$SELECTED_TABLE" ]; then
  echo "⚠️  No table selected. No newsworthy updates found."
  exit 0
fi

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "🏃 Dry run mode - stopping before data fetch"
  exit 0
fi

# Step 2: Fetch data
echo ""
echo "📥 Step 2: Fetching data for table $SELECTED_TABLE..."
Rscript r-tools/fetch_table.R "$SELECTED_TABLE" "$OUTPUT_DIR"

# Check for output file
DATA_FILE="$OUTPUT_DIR/data_${SELECTED_TABLE//-/_}.json"
if [ ! -f "$DATA_FILE" ]; then
  echo "❌ Data fetch failed - no output file"
  exit 1
fi

echo "✅ Data saved to: $DATA_FILE"

# Step 3: Generate article
# NOTE: This step requires Claude Code to be invoked
# In an automated environment, this would call the Claude API
echo ""
echo "📝 Step 3: Article generation required"
echo ""
echo "To generate the article, run Claude Code with:"
echo ""
echo "  /the-daily-generator $SELECTED_TABLE"
echo ""
echo "Or manually:"
echo "  1. Review data: cat $DATA_FILE"
echo "  2. Create article in docs/en/<slug>/index.md"
echo "  3. Create French version in docs/fr/<slug>/index.md"
echo "  4. Update docs/en/index.md and docs/fr/index.md"
echo "  5. Run: npm run build"
echo ""

# For fully automated mode (with Claude API), uncomment:
# claude --prompt "Generate articles for table $SELECTED_TABLE using /the-daily-generator"

# Step 4: Build (only if articles exist)
# echo ""
# echo "🔨 Step 4: Building site..."
# npm run build

# Step 5: Publish (only if build succeeds)
# echo ""
# echo "🚀 Step 5: Publishing..."
# git add docs/ output/
# git commit -m "Add: <headline> - generated by D-AI-LY"
# git push

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  Pipeline complete. Review and run /the-daily-generator"
echo "═══════════════════════════════════════════════════════════════════"
