#!/bin/bash
#
# The D-AI-LY - Automated Pipeline Runner
#
# This script is designed to be run by launchd/cron for autonomous daily operation.
# It runs the full pipeline: discover → fetch → generate → publish
#
# Usage:
#   ./run_pipeline.sh              # Full pipeline with Claude Code
#   ./run_pipeline.sh --prep-only  # Discovery + fetch only (for manual generation)
#
# Environment:
#   Requires R (with cansim package), Node.js, and Claude Code CLI
#

set -e

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_DIR/output"
LOG_DIR="$SCRIPT_DIR/logs"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="$LOG_DIR/pipeline_$TIMESTAMP.log"

# Paths (adjust if R/Node installed elsewhere)
export PATH="/usr/local/bin:/opt/homebrew/bin:$HOME/.nvm/versions/node/v20.10.0/bin:$PATH"

# ============================================================================
# Logging
# ============================================================================

mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" | tee -a "$LOG_FILE" >&2
}

# ============================================================================
# Parse Arguments
# ============================================================================

PREP_ONLY=false
SPECIFIC_TABLE=""

for arg in "$@"; do
    case $arg in
        --prep-only)
            PREP_ONLY=true
            ;;
        --table=*)
            SPECIFIC_TABLE="${arg#*=}"
            ;;
    esac
done

# ============================================================================
# Main Pipeline
# ============================================================================

log "═══════════════════════════════════════════════════════════════════"
log "  THE D-AI-LY - Automated Pipeline"
log "  Started: $TIMESTAMP"
log "═══════════════════════════════════════════════════════════════════"

cd "$PROJECT_DIR"

# Step 1: Discovery
log ""
log "Step 1: Running topic discovery..."

if [ -n "$SPECIFIC_TABLE" ]; then
    log "Using specified table: $SPECIFIC_TABLE"
    SELECTED_TABLE="$SPECIFIC_TABLE"
else
    Rscript r-tools/discover_topics.R --configured --json --output="$OUTPUT_DIR" >> "$LOG_FILE" 2>&1

    if [ -f "$OUTPUT_DIR/discovery_results.json" ]; then
        SELECTED_TABLE=$(python3 -c "
import json
with open('$OUTPUT_DIR/discovery_results.json') as f:
    data = json.load(f)
    if data.get('recommendation'):
        print(data['recommendation']['table_number'])
")
        log "Recommended table: $SELECTED_TABLE"
    else
        log_error "Discovery failed - no results file"
        exit 1
    fi
fi

if [ -z "$SELECTED_TABLE" ]; then
    log "No newsworthy updates found. Pipeline complete."
    exit 0
fi

# Step 2: Fetch data
log ""
log "Step 2: Fetching data for table $SELECTED_TABLE..."

Rscript r-tools/fetch_table.R "$SELECTED_TABLE" "$OUTPUT_DIR" >> "$LOG_FILE" 2>&1

DATA_FILE="$OUTPUT_DIR/data_${SELECTED_TABLE//-/_}.json"
if [ ! -f "$DATA_FILE" ]; then
    log_error "Data fetch failed - no output file"
    exit 1
fi

log "Data saved to: $DATA_FILE"

# Step 3: Check if prep-only mode
if [ "$PREP_ONLY" = true ]; then
    log ""
    log "Prep-only mode - stopping before article generation"
    log ""
    log "To generate the article manually, run:"
    log "  claude \"/the-daily-generator $SELECTED_TABLE\""
    log ""
    exit 0
fi

# Step 4: Generate article with Claude Code
log ""
log "Step 3: Generating article with Claude Code..."

# Check if Claude Code is available
if ! command -v claude &> /dev/null; then
    log_error "Claude Code CLI not found. Install with: npm install -g @anthropic-ai/claude-code"
    log ""
    log "To generate manually, run:"
    log "  claude \"/the-daily-generator $SELECTED_TABLE\""
    exit 1
fi

# Run Claude Code with the generator skill
# Using --print for non-interactive mode
claude --print "/the-daily-generator $SELECTED_TABLE" >> "$LOG_FILE" 2>&1

if [ $? -ne 0 ]; then
    log_error "Article generation failed"
    exit 1
fi

log "Article generated successfully"

# Step 5: Build site
log ""
log "Step 4: Building site..."

npm run build >> "$LOG_FILE" 2>&1

log "Site built successfully"

# Step 6: Commit and push (optional - uncomment to enable)
# log ""
# log "Step 5: Publishing..."
# git add docs/ output/
# if ! git diff --staged --quiet; then
#     git commit -m "Add: Article for table $SELECTED_TABLE - generated by D-AI-LY"
#     git push
#     log "Published successfully"
# else
#     log "No changes to publish"
# fi

log ""
log "═══════════════════════════════════════════════════════════════════"
log "  Pipeline complete!"
log "  Log saved to: $LOG_FILE"
log "═══════════════════════════════════════════════════════════════════"
